Development
pavlegich/gophermart pull request #2
Opened 2023-10-08 11:32 UTC by pavlegich

2023-10-22 07:50 UTC, popoffvg requested changes

2023-10-22 07:50 UTC, popoffvg commented on internal/domains/user/controllers/http/handler.go
> +	if _, err := buf.ReadFrom(r.Body); err != nil {
`buf.ReadFrom` не закрывает тело запроса

2023-10-22 07:50 UTC, popoffvg commented on internal/domains/user/controllers/http/handler.go
> +		logger.Log.Info("HandleRegister: read request body failed",
Не стоит ошибки логгировать как Info

2023-10-22 07:50 UTC, popoffvg commented on internal/domains/user/repository/repository.go
> +		if err == sql.ErrNoRows {
Стоит всегда проверять через errors.Is

2023-10-22 07:50 UTC, popoffvg commented on internal/domains/user/repository/repository.go
> +		} else {
Не стоит в обработке ошибок использовать `if else`. Стоит использовать ранний return. Ранний return более читаемый и расширяемый при изменении логики обработки ошибки.


```go
if errors.Is(err, sql.ErrNoRows){
    return nil, fmt.Errorf("GetUserByLogin: scan row failed %w", errs.ErrUserNotFound)
}
if err != nil{
     return nil, fmt.Errorf("GetUserByLogin: scan row failed %w", err)
}
```

2023-10-22 07:50 UTC, popoffvg commented on internal/domains/user/repository/repository.go
> +	tx, err := r.db.Begin()
Здесь не нужна транзакция. Транзакцию стоит открывать, если нам нужно получить консистентный данные на какой-то момент времени или установить блокировку

Лишние транзакции:
1. Удержания соединения с БД
2. Лишние сетевые вызовы

БД позаботится об открытии транзакции за нас в случае обычного select

2023-10-22 07:50 UTC, popoffvg commented on internal/domains/user/repository/repository.go
> +	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(u.Password), bcrypt.DefaultCost)
Логика генерации пароля должна быть в домене, а не в репозитория

2023-10-22 07:50 UTC, popoffvg commented on internal/domains/user/repository/repository.go
> +	id := tx.QueryRowContext(ctx, "SELECT id FROM users WHERE login = $1", u.Login)
Это проверка не работает в случае одновременных запросов на вставку. 

В таких случаях стоит делать уникальный индекс для исключения вставки одинаковых значений и переложить работу по проверке на СУБД

2023-10-22 07:50 UTC, popoffvg commented on internal/domains/order/repository/repository.go
> +	rows, err := tx.QueryContext(ctx, "SELECT id, number, user_id, status, accrual, created_at FROM orders WHERE user_id = $1 "+
Не хватает индекса по условия WHERE

2023-10-22 07:50 UTC, popoffvg commented on internal/domains/order/repository/repository.go
> +	userID := tx.QueryRowContext(ctx, "SELECT user_id FROM orders WHERE number = $1", ord.Number)
Есть уникальный индекс, стоит обрабатывать ошибку проверку уникальности от БД

2023-10-22 07:50 UTC, popoffvg commented on internal/domains/order/repository/repository.go
> +	if storedStatus == "INVALID" || storedStatus == "PROCESSED" {
Логика запрета сохранения должна быть уровнем выше. 
С такой проверкой нужно делать SELECT FOR UPDATE

2023-10-22 07:50 UTC, popoffvg commented on internal/domains/order/repository/repository.go
> +		statement, err := tx.PrepareContext(ctx, "INSERT INTO balances "+
Лучше не делать PrepareStatement в одиночных запросах, усложняет читаемость и не приносит пользы. Заставляешь СУБД держать кеш разобранного запроса.

Лучше пусть сама решит нужно ей держать кеш или нет

2023-10-22 07:50 UTC, popoffvg commented on internal/domains/order/repository/repository.go
> +			"(action, amount, user_id, order_number) VALUES ('ACCRUAL', $1, $2, $3)")
Если в этом методе вставляешь записи в баланс, то он должен называться CreateOrder, т.к. Save подразумевает и создание и сохранение.

2023-10-22 07:50 UTC, popoffvg commented on internal/domains/order/repository/repository.go
> +	rows, err := tx.QueryContext(ctx, "SELECT id, number, user_id, status, accrual, created_at FROM orders "+
В go есть мультистроковые литералы \`\`. Можно не писать "" + ""

2023-10-22 07:50 UTC, popoffvg commented on internal/domains/order/repository/repository.go
> +	rows, err := tx.QueryContext(ctx, "SELECT id, number, user_id, status, accrual, created_at FROM orders "+
В таких запросах всегда следует устанавливать ограничение на размер выборки. 

При длительных простоях и средней нагрузке запрос может положить базу

2023-10-23 12:35 UTC, pavlegich commented on internal/domains/order/repository/repository.go
> +	rows, err := tx.QueryContext(ctx, "SELECT id, number, user_id, status, accrual, created_at FROM orders "+
Не очень понимаю, как это можно реализовать, так как для проверки нужны все записи таблицы. Возможно, стоит добавить balance для пользователя

2023-10-23 12:37 UTC, pavlegich commented on internal/domains/order/repository/repository.go
> +	userID := tx.QueryRowContext(ctx, "SELECT user_id FROM orders WHERE number = $1", ord.Number)
Это совсем не понял, нужно пояснение 😐

2023-10-23 12:38 UTC, pavlegich commented on internal/domains/order/repository/repository.go
> +	rows, err := tx.QueryContext(ctx, "SELECT id, number, user_id, status, accrual, created_at FROM orders WHERE user_id = $1 "+
Что имеется ввиду под индексом? Индекса для чего не хватает?

2023-10-23 12:39 UTC, pavlegich commented on internal/domains/user/repository/repository.go
> +	id := tx.QueryRowContext(ctx, "SELECT id FROM users WHERE login = $1", u.Login)
У меня в таблице id primary key, login unique, он же уже должен исключать автоматически

2023-10-23 14:16 UTC, pavlegich commented on internal/domains/order/repository/repository.go
> +	if storedStatus == "INVALID" || storedStatus == "PROCESSED" {
Лучше не давать изменять, если уже обработано

2023-10-30 06:47 UTC, popoffvg approved these changes

2023-10-30 06:55 UTC, merged